#iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
  # Forward Position Controllers ---------------------------------------
  manipulator_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

    gains:
      kmriiwa_joint_1: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_2: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_3: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_4: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_5: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_6: {p: 1, i: 0, d: 0, i_clamp: 0}
      kmriiwa_joint_7: {p: 1, i: 0, d: 0, i_clamp: 0}


    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  endeffector_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - Slider01
      - Slider02

    gains:
      Slider01: {p: 1, i: 0, d: 0, i_clamp: 2000}
      Slider02: {p: 1, i: 0, d: 0, i_clamp: 2000}
    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
