local_costmap:
  global_frame: map
  static_map: true

  plugins:
  - {name: static,      type: "costmap_2d::StaticLayer"}
  - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
  # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


# local_costmap:
#   global_frame: $(arg robot_name)_odom
#   static_map: false
#   rolling_window: true
#   width: 5
#   height: 5

#   plugins:
#   - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
#   # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}