controller_list:
  - name: fake_kmriiwa_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - kmriiwa_joint_1
      - kmriiwa_joint_2
      - kmriiwa_joint_3
      - kmriiwa_joint_4
      - kmriiwa_joint_5
      - kmriiwa_joint_6
      - kmriiwa_joint_7
  - name: fake_kmriiwa_endeffector_controller
    type: $(arg fake_execution_type)
    joints:
      - Slider01
      - Slider02
initial:  # Define initial robot poses per group
  - group: kmriiwa_manipulator
    pose: home
  - group: kmriiwa_endeffector
    pose: open