# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: $(arg robot_name)_manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7
    # - Slider01
    # - Slider02
    
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: /$(arg robot_name)/arm/manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

  - name: /$(arg robot_name)/arm/endeffector_controller
    action_ns: follow_joint_trajectory
    default: True
    # type: effort_controllers/JointTrajectoryController
    type: FollowJointTrajectory
    joints:
      - Slider01
      - Slider02
    gains:
      Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
      Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}

# kmriiwa_endeffector_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - Slider01
#     - Slider02
#   gains:
#     Slider01:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     Slider02:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1