# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: $(arg robot_name)_manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7
    - Slider01
    - Slider02
    
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  # - name: /$(arg robot_name)/arm/manipulator_controller
  - name: /$(arg robot_name)/manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

    gains:
      kmriiwa_joint_1:
        p: 1000
        d: 50
        i: 10
        i_clamp: 100
      kmriiwa_joint_2:
        p: 5000
        d: 30
        i: 100
        i_clamp: 400
      kmriiwa_joint_3:
        p: 5000
        d: 50
        i: 10
        i_clamp: 100
      kmriiwa_joint_4:
        p: 200
        d: 20
        i: 10
        i_clamp: 100
      kmriiwa_joint_5:
        p: 100
        d: 10
        i: 0.1
        i_clamp: 100
      kmriiwa_joint_6:
        p: 10
        d: 1
        i: 0.1
        i_clamp: 100
      kmriiwa_joint_7:
        p: 10
        d: 1
        i: 0.1
        i_clamp: 100

    # gains:
    #   kmriiwa_joint_1: {p: 1000, i: 40, d: 20, i_clamp: 100}
    #   kmriiwa_joint_2: {p: 9000, i: 1500, d: 50, i_clamp: 2000}
    #   kmriiwa_joint_3: {p: 1000, i: 40, d: 20, i_clamp: 100}
    #   kmriiwa_joint_4: {p: 2500, i: 100, d: 30, i_clamp: 150}
    #   kmriiwa_joint_5: {p: 250, i: 30, d: 20, i_clamp: 100}
    #   kmriiwa_joint_6: {p: 800, i: 50, d: 15, i_clamp: 100}
    #   kmriiwa_joint_7: {p: 100, i: 5, d: 1, i_clamp: 100}


  # - name: /$(arg robot_name)/arm/endeffector_controller
  - name: /$(arg robot_name)/endeffector_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Slider01
      - Slider02
    gains:
      Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
      Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}

# kmriiwa_endeffector_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - Slider01
#     - Slider02
#   gains:
#     Slider01:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     Slider02:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1